name: social_share_example
description: Demonstrates how to use the social_share plugin
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  screenshot: ^1.2.3
  path_provider: ^2.0.5
  http:
  image_picker: ^0.8.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  social_share:
    path: ../

flutter:
  uses-material-design: true